/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adamasmaca;

/**
 *
 * @author msı
 */

public class SifreEkran extends javax.swing.JFrame {
    private int yanlisSayisi = 0;
    private final boolean belirlemeModuMu;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SifreEkran.class.getName());
    
    public SifreEkran() {
        initComponents();
  

        java.awt.Color anaArkaPlan = new java.awt.Color(74, 55, 40);
        java.awt.Color panelArkaPlan = new java.awt.Color(101, 77, 58);
        java.awt.Color yaziRengi = new java.awt.Color(245, 240, 225);
        java.awt.Color canliYesil = new java.awt.Color(40, 167, 69);
        java.awt.Color neonSari = new java.awt.Color(255, 193, 7);

       getContentPane().setBackground(anaArkaPlan);

        lblBaslik.setForeground(neonSari);
        lblBaslik.setBackground(panelArkaPlan);
        lblBaslik.setOpaque(true);

        lblSifre.setForeground(yaziRengi);
        lblTekrar.setForeground(yaziRengi);

        lblHata.setForeground(new java.awt.Color(220, 53, 69)); 

        txtSifre1.setBackground(panelArkaPlan);
        txtSifre1.setForeground(yaziRengi);
        txtSifre1.setCaretColor(yaziRengi);

        txtSifre2.setBackground(panelArkaPlan);
        txtSifre2.setForeground(yaziRengi);
        txtSifre2.setCaretColor(yaziRengi);

        btnGiris.setBackground(canliYesil);
        btnGiris.setForeground(yaziRengi);

        this.setSize(420, 340);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistem Kimlik Doğrulaması"); 

        DosyaYonetici.klasorleriOlustur();
        DosyaYonetici.kelimelerOlustur();
        belirlemeModuMu = !DosyaYonetici.sifreVarMi();

        if (belirlemeModuMu) {
            lblBaslik.setText("Kurulum: Sistem Parolası Oluşturun");
            btnGiris.setText("Parolayı Onayla");
            lblSifre.setText("Parola:");
            lblTekrar.setText("Doğrulama:");
        } else {
            lblBaslik.setText("Kelime Arenası: Giriş Yapın");
            btnGiris.setText("Sisteme Bağlan");
            lblTekrar.setVisible(false);
            txtSifre2.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBaslik = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        txtSifre1 = new javax.swing.JPasswordField();
        lblTekrar = new javax.swing.JLabel();
        txtSifre2 = new javax.swing.JPasswordField();
        btnGiris = new javax.swing.JButton();
        lblHata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));

        lblBaslik.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblBaslik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaslik.setText("Kelime Arenası : Giriş Yapın");

        lblSifre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSifre.setText("Şifre : ");

        txtSifre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSifre1.setToolTipText("");
        txtSifre1.addActionListener(this::txtSifre1ActionPerformed);

        lblTekrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTekrar.setText("Tekrar : ");

        txtSifre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSifre2.addActionListener(this::txtSifre2ActionPerformed);

        btnGiris.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGiris.setText("Giriş Yap ");
        btnGiris.addActionListener(this::btnGirisActionPerformed);

        lblHata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTekrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSifre1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtSifre2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblHata, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnGiris))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifre)
                    .addComponent(txtSifre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTekrar)
                    .addComponent(txtSifre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnGiris)
                .addGap(37, 37, 37)
                .addComponent(lblHata)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        // TODO add your handling code here:
        if (belirlemeModuMu) {
            sifreBelirle();
        } else {
            sifreGiris();
        }
    }

        private void sifreBelirle() {
    String s1 = new String(txtSifre1.getPassword()).trim();
    String s2 = new String(txtSifre2.getPassword()).trim();
    if (s1.isEmpty()) {
        lblHata.setText("Parola alanı boş bırakılamaz!");
        return;
    }
    if (!s1.equals(s2)) {
        lblHata.setText("Girdiğiniz parolalar uyuşmuyor!");
        return;
    }
    DosyaYonetici.sifreKaydet(s1);
    DosyaYonetici.logKaydet("Sistem Parolası Oluşturuldu");
    javax.swing.JOptionPane.showMessageDialog(null, "Güvenlik ayarları başarıyla kaydedildi!");
    oyunuAc();
}

private void sifreGiris() {
    String girilen = new String(txtSifre1.getPassword()).trim();
    String kayitli = DosyaYonetici.sifreOku();
    if (girilen.equals(kayitli)) {
        DosyaYonetici.logKaydet("Oturum Açıldı");
        oyunuAc();
    } else {
        yanlisSayisi++;
        DosyaYonetici.logKaydet("Başarısız Giriş Denemesi (" + yanlisSayisi + ")");
        txtSifre1.setText("");
        if (yanlisSayisi >= 3) {
            javax.swing.JOptionPane.showMessageDialog(this, "Çok sayıda başarısız deneme! Sistem kilitleniyor.");
            System.exit(0);
        } else {
            lblHata.setText("Erişim Reddedildi! Kalan deneme:" + (3 - yanlisSayisi));
        }
    }
}


private void oyunuAc() {
    new OyunEkran().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnGirisActionPerformed

    private void txtSifre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifre1ActionPerformed
        // TODO add your handling code here:
        if (belirlemeModuMu) {
            sifreBelirle();
        } else {
            sifreGiris();
        }
    }//GEN-LAST:event_txtSifre1ActionPerformed

    private void txtSifre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifre2ActionPerformed
        // TODO add your handling code here:
        sifreBelirle();
    }//GEN-LAST:event_txtSifre2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new SifreEkran().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel lblBaslik;
    private javax.swing.JLabel lblHata;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JLabel lblTekrar;
    private javax.swing.JPasswordField txtSifre1;
    private javax.swing.JPasswordField txtSifre2;
    // End of variables declaration//GEN-END:variables
}
